export const drivingTips = [
  'Give yourself extra following distance when roads are wet or icy.',
  'School-zone speed limits apply when children are present.',
  'A flashing red light works like a stop sign: stop, check, then proceed.',
  'Low beams are safer than high beams in fog.',
  'Learners must keep a zero blood alcohol level.',
  'Scan intersections early, even when you have the right of way.',
  'Signal before changing lanes, then shoulder check before you move.',
  'Leave room around large trucks because their blind spots are much bigger.',
  'Wet leaves can reduce traction nearly as much as ice.',
  'At railway crossings, look both ways and never stop on the tracks.',
  'A yellow light means stop if you can do so safely.',
  'Reduce speed before curves, not while you are already turning.',
  'Keep your windshield washer fluid topped up before winter drives.',
  'Use parking lights only for parking, not for driving in poor visibility.',
  'A safe following gap grows with speed, weather, and traffic density.',
  'Check mirrors often, but do not rely on mirrors alone before lane changes.',
  'Watch for pedestrians before turning right on red where it is allowed.',
  'Emergency vehicles can approach from any direction, including behind you.',
  'Plan your lane early so you do not need a last-second merge.',
  'If you miss a turn, continue safely and reroute instead of making a sudden move.',
  'Children can be hard to see around parked vehicles and school buses.',
  'Speed limits are maximums, not targets, when road conditions are poor.',
  'Use gentle steering, braking, and acceleration on slippery roads.',
  'Fatigue slows reaction time even when you have had no alcohol.',
] as const;
